obstacle_range: 6
raytrace_range: 8.5
footprint: [[0.20, 0.20], [0.20, -0.20], [-0.22, -0.20], [-0.22, 0.20]]
# footprint: [[0.25, 0.25], [0.25, -0.20], [-0.22, -0.20], [-0.22, 0.25]]
inflation_radius: 0.35
transform_tolerance: 0.5

observation_sources: scan
scan:
  data_type: LaserScan
  topic: ebot/laser/scan
  marking: true
  clearing: true

map_type: costmap
