TrajectoryPlannerROS:
  max_vel_x: 1.6
  min_vel_x: 0.01
  max_vel_theta: 3.0
  min_vel_theta: -3.0
  min_in_place_vel_theta: 1.0
  acc_lim_theta: 2.5
  acc_lim_x: 1.5
  acc_lim_y: 1.5
  holonomic_robot: false
  meter_scoring: true
