controller_list:
  - name: fake_ur5_1_planning_group_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_hand_controller
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses.
  - group: ur5_1_planning_group
    pose: allZeros
  - group: hand
    pose: open